"""
database.sessions – CRUD helpers for game session documents.

Each session document stores the persona, full chat history, timing info,
and the final evaluation result once the game ends.
"""

import time
from datetime import datetime, timezone

from database import get_db


def create_session(
    session_id: str,
    name: str,
    mode: str,
    persona: str,
    opening: str,
    duration: int,
) -> dict:
    """
    Insert a new session document and return it.

    The opening message from the AI persona is stored as the first history entry
    so that next_user_message() always has at least one turn to react to.

    Args:
        session_id: Hex UUID used as the MongoDB _id.
        name:       Display name chosen by the player (truncated to 24 chars).
        mode:       Game mode (classic / interview / chaos / jailbreak).
        persona:    Hidden persona description generated by the LLM.
        opening:    The persona's first message to the player.
        duration:   Session length in seconds (GAME_DURATION from main.py).

    Returns:
        The newly created session dict (includes ends_at for the response body).
    """
    db = get_db()
    now = time.time()

    session = {
        "_id": session_id,
        "name": name[:24],  # cap display name length
        "mode": mode,
        "persona": persona,
        "history": [
            {
                "from": "ai_user",
                "text": opening,
                "at": now,
            }
        ],
        "started_at": now,
        "ends_at": now + duration,
        "finished": False,
        # datetime field used by the TTL index to auto-expire old sessions.
        "created_at": datetime.now(timezone.utc),
    }

    db["sessions"].insert_one(session)
    return session


def get_session(session_id: str) -> dict | None:
    """Return the session document for session_id, or None if not found."""
    db = get_db()
    return db["sessions"].find_one({"_id": session_id})


def update_session(session_id: str, updates: dict) -> None:
    """Apply a $set patch to the session document."""
    db = get_db()
    db["sessions"].update_one({"_id": session_id}, {"$set": updates})


def add_history_entry(session_id: str, entry: dict) -> None:
    """Append a single turn to the session's history array."""
    db = get_db()
    db["sessions"].update_one({"_id": session_id}, {"$push": {"history": entry}})


def delete_session(session_id: str) -> None:
    """Permanently delete a session document (used in tests / admin tooling)."""
    db = get_db()
    db["sessions"].delete_one({"_id": session_id})
